### ISSUE TITLE
Loading local modules in TypeScript based lambda's doesn't work

### ISSUE THREAD

**Issue by jaapvanblaaderen** [vvo/aws-lambda-nodejs-rollup#1]
Example Lambda:

```
import { APIGatewayProxyEvent, Context } from 'aws-lambda';
import { SomeModule } from './some-module';

export function handler(event: APIGatewayProxyEvent, context: Context): void {
   //...
}
```

Webpack Error:
```
   'ERROR in ./lib/app/lambda.ts\n' +
       "Module not found: Error: Can't resolve './some-module' in '/<repo-dir>/lib/app'\n" +
```

**Comment by vvo** [comment]
@jaapvanblaaderen Hey there, is this working for you now with the latest release? Also, do you have any feedback for this construct? It's pretty new so just let me know!

**Comment by jaapvanblaaderen** [comment]
Works like a charm now for my simple app, thanks for putting in the effort! In a previous version I had a few dependency warning but I guess you have fixed those recently? It took me a while to find your AWS CDK issue (and thus the cause why it is so slow in the first place...) But this is almost instant so that's great.

Curious to see how the CDK team will fix the issue. It looks like they want to allow you to run parcel locally: https://github.com/aws/aws-cdk/pull/9632/files#diff-d1ca980a28afad065f42db45da422528R107

**Comment by vvo** [comment]
> I had a few dependency warning but I guess you have fixed those recently?

Hmm I do not recall doing something about that but: the output is now hidden unless there's a real error, which is maybe what's doing it for you!

> Curious to see how the CDK team will fix the issue. It looks like they want to allow you to run parcel locally: [aws/aws-cdk#9632 (files)](https://github.com/aws/aws-cdk/pull/9632/files#diff-d1ca980a28afad065f42db45da422528R107)

One thing to note is that it will always be parcel for now, and I feel parcel customization might be limiting at some point/people will want to pass webpack options.

Do not hesitate to open new issues, thanks a lot for using this!
